# Generated by Django 2.2.1 on 2019-05-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('school_id', models.IntegerField()),
                ('school_email', models.EmailField(max_length=254)),
                ('is_teacher', models.BooleanField()),
            ],
        ),
    ]
